/**
 * Seeds a real Operator (casino) on THIS platform instance for the demo-operator/
 * website to integrate against over HTTP, then boots the platform and serves.
 *
 * Unlike dev-seed.ts (which uses the in-memory SandboxWallet), this instance's
 * wallet is a WebhookWallet — every debit/credit/rollback/balance call is signed
 * and sent to demo-operator's own /wallet/* endpoints, proving the real
 * provider↔casino wallet integration works over the wire (see GUIDE.md and
 * platform/src/modules/wallet/webhook-wallet.ts).
 *
 * State is in-memory only (no Postgres) — every run is a fresh operator with a
 * fresh API credential + webhook secret, written to demo-operator/.env. Restart
 * BOTH processes together after re-running this script.
 *
 *   npx tsx scripts/seed-demo-operator.ts
 *   # or
 *   npm run dev:seed:demo-operator
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildContainer, seedBootstrapAdmin } from "../src/container";
import { buildApp } from "../src/app";
import { createLogger } from "../src/lib/logger";
import { WebhookWallet } from "../src/modules/wallet/webhook-wallet";

const PORT = Number(process.env.PORT ?? 8080);
const DEMO_OPERATOR_PORT = Number(process.env.DEMO_OPERATOR_PORT ?? 4000);
const CURRENCY = "GEL";
const GAME_CODE = "bananax";
const ORIGIN = "demo-operator.local";
const DEMO_TTL_SECONDS = Number(process.env.DEMO_TOKEN_TTL_SECONDS ?? 60 * 60 * 24 * 30); // a month — this token only guards a local dev instance.

const cfg = {
  launchSecret: process.env.LAUNCH_TOKEN_SECRET ?? "dev-launch-secret-change-me",
  sessionSecret: process.env.SESSION_TOKEN_SECRET ?? "dev-session-secret-change-me",
  adminSecret: process.env.ADMIN_TOKEN_SECRET ?? "dev-admin-secret-change-me",
  hmacSkewSeconds: 30,
  rateLimitPerMin: 10_000,
  bootstrapAdminUsername: process.env.BOOTSTRAP_ADMIN_USERNAME ?? "admin",
  bootstrapAdminPassword: process.env.BOOTSTRAP_ADMIN_PASSWORD ?? "change-me-admin",
  // Local dev convenience: skip the authenticator-enrollment step entirely.
  totpRequired: (process.env.ADMIN_TOTP_REQUIRED ?? "false").toLowerCase() === "true"
};

async function main(): Promise<void> {
  const c = buildContainer(cfg, { walletFactory: (mgmt) => new WebhookWallet(mgmt) });

  const op = c.mgmt.createOperator({ name: "Demo Operator Site", slug: "demo-operator-site", default_currency: CURRENCY });
  c.mgmt.addDomain(op.id, ORIGIN, "prod");

  const game = c.mgmt.registerGame({ code: GAME_CODE, title: "Banana X" });
  let mc = c.mgmt.createMathConfig({
    game_id: game.id,
    version: "3.0.0",
    rtp_profile_key: "bananax",
    theoretical_rtp: 96.38,
    config_hash: "sha256:demo-operator"
  });
  mc = c.mgmt.approveMathConfig(c.mgmt.submitMathConfigForReview(mc.id).id, "math-lead");
  c.mgmt.assignGame({
    operator_id: op.id,
    game_id: game.id,
    math_config_id: mc.id,
    currency: CURRENCY,
    allowed_bets: [1, 5, 10, 50]
  });
  // Casino-controlled lobby display, set here the same way the Operator's own
  // console would (PATCH /admin/v1/operator-games/:id) — see the Games tab.
  const entitlement = c.mgmt.listOperatorGames(op.id)[0];
  c.mgmt.updateOperatorGameDisplay(entitlement.id, { display_name: "Banana X — Lucky Bananas Special", sort_order: 0, lobby_enabled: true }, "seed-script");

  const issued = c.mgmt.issueCredential(op.id, "prod");
  const webhookUrl = `http://127.0.0.1:${DEMO_OPERATOR_PORT}/wallet`;
  const webhook = c.mgmt.setWebhook(op.id, webhookUrl);

  const adminToken = c.adminAuth.mintToken(
    { admin_id: "demo-operator-site-admin", scope: "operator", operator_id: op.id, role: "operator_admin" },
    DEMO_TTL_SECONDS
  );

  // Also seed a real login (username + password + TOTP-on-first-use) for this
  // Operator so you can sign into the platform's OWN console at /admin and watch
  // the dashboard reflect activity generated by the demo site.
  seedBootstrapAdmin(c);
  let operatorAdmin: { username: string; temp_password: string } | null = null;
  if (!c.adminAccounts.getByUsername("demo-operator-site")) {
    const created = c.adminAccounts.create(
      { username: "demo-operator-site", scope: "operator", operator_id: op.id, role: "operator_admin" },
      "seed-demo-operator"
    );
    operatorAdmin = { username: created.account.username, temp_password: created.temp_password };
  }

  const envPath = join(__dirname, "..", "..", "demo-operator", ".env");
  const envContents = [
    `PLATFORM_URL=http://127.0.0.1:${PORT}`,
    `PLATFORM_OPERATOR_ID=${op.id}`,
    `PLATFORM_API_KEY_ID=${issued.credential.api_key_id}`,
    `PLATFORM_API_SECRET=${issued.api_secret}`,
    `PLATFORM_WEBHOOK_SECRET=${webhook.secret}`,
    `PLATFORM_ADMIN_TOKEN=${adminToken}`,
    `PLATFORM_ORIGIN=${ORIGIN}`,
    `GAME_CODE=${GAME_CODE}`,
    `CURRENCY=${CURRENCY}`,
    `PORT=${DEMO_OPERATOR_PORT}`,
    `STARTING_BALANCE=1000`,
    ""
  ].join("\n");
  writeFileSync(envPath, envContents, "utf8");

  const app = buildApp({ logger: createLogger({ level: "info", pretty: true, env: "local" }), container: c });
  await app.listen({ host: "127.0.0.1", port: PORT });

  const base = `http://127.0.0.1:${PORT}`;
  // eslint-disable-next-line no-console
  console.log(
    [
      "",
      "─────────────────────────────────────────────────────────────────────",
      `  Platform ready on ${base} — wallet is a WebhookWallet (real HTTP callback)`,
      "─────────────────────────────────────────────────────────────────────",
      "",
      `  Seeded Operator:  'demo-operator-site' (${op.id})`,
      `  Wrote credentials + tokens to: demo-operator/.env`,
      "",
      "  Next step, in a SECOND terminal:",
      "    cd demo-operator && npm install && npm run dev",
      "",
      `  Then open http://127.0.0.1:${DEMO_OPERATOR_PORT} and register a player.`,
      "",
      `  Watch it in the platform's own console: ${base}/admin`,
      operatorAdmin
        ? `    username: ${operatorAdmin.username}   one-time password: ${operatorAdmin.temp_password}`
        : "    (account already existed — reuse your existing password)",
      "",
      "  Ctrl+C to stop. Re-run this script to reset everything (fresh in-memory",
      "  state + fresh demo-operator/.env) — restart demo-operator's server too.",
      "─────────────────────────────────────────────────────────────────────"
    ].join("\n")
  );
}

void main();
